#!/usr/bin/env bash
set -euo pipefail

# replicate-env.sh — clone an existing env into a new one
#
# Usage:
#   replicate-env.sh <source-env> <new-env> <new-domain>
#
# Example:
#   replicate-env.sh prod stage stage.example.com

usage() {
  cat <<'EOF'
Usage: replicate-env.sh <source-env> <new-env> <new-domain>

Examples:
  replicate-env.sh prod stage stage.example.com

What this script does:
  1. Copies envs/<source-env>/ to envs/<new-env>/
  2. Rewrites terraform backend prefix to <project_name>/envs/<new-env>
  3. Generates envs/<new-env>/terraform.tfvars with non-prod defaults
  4. Creates content/<new-env>/<site>/dist placeholders
EOF
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Error: required command '$1' is not installed." >&2
    exit 1
  fi
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

SOURCE_ENV="${1:-}"
NEW_ENV="${2:-}"
NEW_DOMAIN="${3:-}"

if [[ -z "$SOURCE_ENV" || -z "$NEW_ENV" || -z "$NEW_DOMAIN" ]]; then
  usage
  exit 1
fi

if [[ "$NEW_ENV" == "prod" ]]; then
  echo "Error: refusing to overwrite/create 'prod' via replicate-env.sh." >&2
  exit 1
fi

for cmd in cp sed grep awk mkdir; do
  require_cmd "$cmd"
done

SOURCE_DIR="$PROJECT_ROOT/envs/$SOURCE_ENV"
NEW_DIR="$PROJECT_ROOT/envs/$NEW_ENV"

if [[ ! -d "$SOURCE_DIR" ]]; then
  echo "Error: source env directory '$SOURCE_DIR' does not exist." >&2
  exit 1
fi

if [[ -e "$NEW_DIR" ]]; then
  echo "Error: target env directory '$NEW_DIR' already exists." >&2
  exit 1
fi

echo "Cloning env: ${SOURCE_ENV} -> ${NEW_ENV}"
echo "New domain:  ${NEW_DOMAIN}"
echo

cp -r "$SOURCE_DIR" "$NEW_DIR"

PROJECT_NAME="$(grep -E '^project_name\s*=' "$SOURCE_DIR/terraform.tfvars.example" 2>/dev/null \
  | head -1 | sed 's/.*= *"//' | sed 's/"$//')"
if [[ -z "$PROJECT_NAME" ]]; then
  PROJECT_NAME="$(grep -E '^project_name\s*=' "$SOURCE_DIR/variables.tf" \
    | head -1 | sed 's/.*= *"//' | sed 's/"$//')"
fi
if [[ -z "$PROJECT_NAME" ]]; then
  PROJECT_NAME="gcp-edge"
fi

if [[ -f "$NEW_DIR/main.tf" ]]; then
  sed -i "s|prefix = \"${PROJECT_NAME}/envs/${SOURCE_ENV}\"|prefix = \"${PROJECT_NAME}/envs/${NEW_ENV}\"|g" "$NEW_DIR/main.tf"
fi

SOURCE_TFVARS="$SOURCE_DIR/terraform.tfvars"
if [[ ! -f "$SOURCE_TFVARS" ]]; then
  SOURCE_TFVARS="$SOURCE_DIR/terraform.tfvars.example"
fi

if [[ ! -f "$SOURCE_TFVARS" ]]; then
  echo "Error: neither terraform.tfvars nor terraform.tfvars.example found in '$SOURCE_DIR'." >&2
  exit 1
fi

project_id="$(grep -E '^project_id\s*=' "$SOURCE_TFVARS" | head -1 | sed 's/.*= *"//' | sed 's/"$//')"
region="$(grep -E '^region\s*=' "$SOURCE_TFVARS" | head -1 | sed 's/.*= *"//' | sed 's/"$//')"
site_domain="$(grep -E '^site_domain\s*=' "$SOURCE_TFVARS" | head -1 | sed 's/.*= *"//' | sed 's/"$//')"
org_domain="$(grep -E '^org_domain\s*=' "$SOURCE_TFVARS" | head -1 | sed 's/.*= *"//' | sed 's/"$//')"
alert_email="$(grep -E '^alert_email\s*=' "$SOURCE_TFVARS" | head -1 | sed 's/.*= *"//' | sed 's/"$//')"
github_org="$(grep -E '^github_org\s*=' "$SOURCE_TFVARS" | head -1 | sed 's/.*= *"//' | sed 's/"$//' || true)"
github_repo="$(grep -E '^github_repo\s*=' "$SOURCE_TFVARS" | head -1 | sed 's/.*= *"//' | sed 's/"$//' || true)"

if [[ -z "$project_id" || -z "$region" || -z "$alert_email" ]]; then
  echo "Error: failed to parse required values from '$SOURCE_TFVARS'." >&2
  exit 1
fi

state_bucket="${project_name}-tfstate-${project_id}"

site_key_main="$(echo "$NEW_DOMAIN" | tr '.-' '__')"
site_key_blogs="blogs_${site_key_main}"

cat > "$NEW_DIR/terraform.tfvars" <<EOF
# Auto-generated by replicate-env.sh
# Source: ${SOURCE_ENV} | Target: ${NEW_ENV}

project_id   = "${project_id}"
region       = "${region}"
project_name = "${project_name}"
environment  = "${NEW_ENV}"
site_domain  = "${site_domain}"
org_domain   = "${org_domain}"
alert_email  = "${alert_email}"

# Lower default budget for non-prod
monthly_budget_limit_usd = 1

sites = {
  ${site_key_main} = {
    domain              = "${NEW_DOMAIN}"
    enable_www_redirect = true
  }
  ${site_key_blogs} = {
    domain              = "blogs.${NEW_DOMAIN}"
    enable_www_redirect = false
  }
}

github_org  = "${github_org}"
github_repo = "${github_repo}"

state_bucket_name = "${state_bucket}"

# Optional
# turnstile_secret = ""
EOF

mkdir -p "$PROJECT_ROOT/content/$NEW_ENV/$site_key_main/dist"
mkdir -p "$PROJECT_ROOT/content/$NEW_ENV/$site_key_blogs/dist"

cat > "$PROJECT_ROOT/content/$NEW_ENV/$site_key_main/dist/index.html" <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${NEW_ENV} - ${site_key_main}</title>
</head>
<body>
  <h1>${NEW_ENV} environment - ${site_key_main}</h1>
  <p>Placeholder content for ${NEW_DOMAIN}</p>
</body>
</html>
EOF

cat > "$PROJECT_ROOT/content/$NEW_ENV/$site_key_blogs/dist/index.html" <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${NEW_ENV} - ${site_key_blogs}</title>
</head>
<body>
  <h1>${NEW_ENV} environment - ${site_key_blogs}</h1>
  <p>Placeholder content for blogs.${NEW_DOMAIN}</p>
</body>
</html>
EOF

cat <<EOF

Created environment '${NEW_ENV}'.

Next steps:
1) Review generated tfvars:
   ${NEW_DIR}/terraform.tfvars

2) Initialize and apply:
   cd ${NEW_DIR}
   terraform init
   terraform plan
   terraform apply

3) Deploy content:
   cd ${PROJECT_ROOT}
   ./scripts/deploy-site.sh --env ${NEW_ENV} ${site_key_main}
   ./scripts/deploy-site.sh --env ${NEW_ENV} ${site_key_blogs}

4) Verify:
   ./scripts/verify-site.sh --env ${NEW_ENV} ${site_key_main}
   ./scripts/verify-site.sh --env ${NEW_ENV} ${site_key_blogs}
EOF